# Generated by Django 5.2.4 on 2026-01-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='tutors', to='app.subject'),
        ),
    ]
