# Generated by Django 5.2.4 on 2026-01-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tutorprofile_is_active_alter_tutorprofile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='tutors', to='app.subject'),
        ),
    ]
